version: '3.1'

services:
  db:
    image: postgres:15.2-alpine3.17
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
      - ./conf/script:/docker-entrypoint-initdb.d
      - ./conf/postgres.conf:/etc/postgresql/postgresql.conf